export const linkStyle = {
  backgroundColor: '#dc6134',
  border: '1px solid #dc6134',
  borderRadius: 3,
  color: 'white',
  display: 'block',
  fontFamily: 'sans-serif',
  fontSize: 14,
  textTransform: 'uppercase',
  lineHeight: 44,
  textAlign: 'center',
  fontWeight: 'bold',
  textDecoration: 'none',
  width: '90%',
  maxWidth: 350,
  textSizeAdjust: 'none',
  whiteSpace: 'nowrap',
  boxShadow: 'inset 0 -1.2px rgba(0, 0, 0, 0.12) !important',
};
